### ISSUE TITLE
Update icon

### ISSUE THREAD

**Issue by mit-mit** [dart-lang/pub-dartlang-dart#1249]
Dart has a new icon, so we should update the Pub site. If possible, we should also tweak the color scheme to match the new colors.

**Comment by anders-sandholm** [comment]
Looks like this has been fixed, landed, and deployed. 
Woohoo.
Thanks @isoos and @jakobr-google

**Comment by mit-mit** [comment]
Re-opening: there is still an issue with font sizes we are tracking down, so this is not entirely fixed
