### ISSUE TITLE
pub server often returns 502s

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/pub-dartlang-dart#94]
_From @Hixie on April 5, 2017 19:30_

We regularly see "HTTP error 502: Bad Gateway" errors when running "pub get".

_Copied from original issue: dart-lang/sdk#29272_

**Comment by kevmoo** [comment]
_From @sethladd on April 5, 2017 19:41_

This affects our CI system.

**Comment by kevmoo** [comment]
_From @sethladd on April 5, 2017 19:42_

cc @kevmoo

**Comment by kevmoo** [comment]
Would you say this is happening more or less lately?

I don't think we're seeing errors at our app level -- I'm guessing this is an app engine issue.

One could imagine adding retry logic to the pub client, though...

**Comment by Hixie** [comment]
I don't think it's happening more on a "failure per attempt" basis, but we're hitting it more in absolute terms because we're using pub more. As flutter gets more popular I expect this to become more and more serious as more and more people use it.

Having the pub tool retry is https://github.com/dart-lang/sdk/issues/29271; this bug is specifically about the pub server itself returning 502s at all.

**Comment by mkustermann** [comment]
I can confirm that every 502 so far came not from our application directly but from GCE infrastructure  in front of it.

Do you see this coming in bursts (i.e. many 502s around the same time) or a single 502 once in a while?

Please: To help diagnose these issues it would be very beneficial to know
  * the exact UTC timestamp when it happened
  * preferably from where it happened (region and/or client ip)
  * maybe a failure log (running pub get with `--verbose` can be useful) 

Feel free to ping me directly when it happens again!

**Comment by Hixie** [comment]
Here's an example:
https://build.chromium.org/p/client.flutter/builders/Mac/builds/3174 (there's a link there to the stdout logs but it doesn't have --verbose enabled for pub, sorry.)
Happened sometime between 2017-04-05 12:24:50 and 12:26:47. Not sure exactly where that is but we believe it's hosted in Google's Cloud infrastructure.

I'll keep an eye out for the next time we hit this and try to answer your questions accurately. Anecdotally I believe the answers are that they happen in groups, that we see it on several unrelated bots at the same time if they happen to all hit pub around the same time, and that it's unrelated to region (that we see it from all our bots and even sometimes in person).

HTTP 502 normally means "the back-end I was trying to talk to failed", so it would make sense that they are coming from GCE, and may indicate that there's some other failure happening at the pub level (maybe GCE timed out waiting for a response, say).

**Comment by goderbauer** [comment]
Here is another failure:
```
Connection closed before full header was received
pub get failed (69)
```
For details: https://uberchromegw.corp.google.com/i/client.flutter/builders/Mac/builds/3179/steps/download%20dependencies/logs/stdio

**Comment by Hixie** [comment]
AppVeyor just saw an isolated 502 while running tests ([logs](https://github.com/dart-lang/pub-dartlang-dart/files/903562/log.1.txt)). I am not aware of any 502s from any other bots at the same time.

**Comment by Hixie** [comment]
Travis just saw:
```
Running 'flutter packages get' in flutter_gallery...      
HTTP error 502: Bad Gateway
package:pub/src/source/hosted.dart 329                    BoundHostedSource._throwFriendlyError
package:pub/src/source/hosted.dart 139                    BoundHostedSource.doGetVersions
===== asynchronous gap ===========================
package:pub/src/source.dart 165                           BoundSource.getVersions
package:pub/src/solver/version_solver.dart 230            SolverCache.getVersions.<fn>
package:pub/src/http.dart 227                             withDependencyType
package:pub/src/solver/version_solver.dart 229            SolverCache.getVersions
===== asynchronous gap ===========================
package:pub/src/solver/unselected_package_queue.dart 121  UnselectedPackageQueue._getNumVersions
===== asynchronous gap ===========================
package:pub/src/solver/unselected_package_queue.dart 50   UnselectedPackageQueue.add
===== asynchronous gap ===========================
package:pub/src/solver/version_selection.dart 68          VersionSelection.select.<fn>
===== asynchronous gap ===========================
dart:async                                                Future.forEach
package:pub/src/solver/version_selection.dart 61          VersionSelection.select
===== asynchronous gap ===========================
package:pub/src/solver/backtracking_solver.dart 308       BacktrackingSolver._solve.<fn>
===== asynchronous gap ===========================
dart:async                                                _completeOnAsyncReturn
package:pub/src/solver/backtracking_solver.dart 312       BacktrackingSolver._solve.<fn>
dart:async                                                _completeOnAsyncReturn
package:pub/src/solver/version_selection.dart 71          VersionSelection.select
This is an unexpected error. Please run
    pub --trace --verbosity=warning get --no-packages-dir --no-precompile
and include the logs in an issue on https://github.com/dart-lang/pub/issues/new
pub get failed (69)
```
...about an hour ago.

**Comment by mkustermann** [comment]
Very infrequently (around 20 per day) we see the following error from the Cloud load balancer:
```
 jsonPayload: {
  statusDetails: "failed_to_pick_backend"    
  @type: "type.googleapis.com/google.cloud.loadbalancing.type.LoadBalancerLogEntry"    
 }
```
which causes a 502.

There is also a [stackoverflow](https://stackoverflow.com/questions/43224170/502-response-coming-from-errors-in-google-cloud-loadbalancer) entry describing the same issue.

**Comment by mkustermann** [comment]
The tracking bug for the pub client is https://github.com/dart-lang/pub/issues/1557 .

**Comment by isoos** [comment]
This [stackoverflow question](http://stackoverflow.com/questions/41305122/some-502-errors-in-gcp-http-load-balancing) has some answers that may be applicable here too.

**Comment by mkustermann** [comment]
@isoos Thanks for the link. I'll follow up with someone from the AppEngine team on this.

**Comment by mkustermann** [comment]
We've notified the App Engine team some time ago and things seemed to have improved since then: Having just checked the logs of the load balancer, it seems the last couple of days there were almost no issues of this sort.

Please keep updating this issue if you continue to see 502 failures.

**Comment by mkustermann** [comment]
It seems like this issue has been resolved. Closing this issue now.

Please re-open if the issue appears again!

**Comment by Hixie** [comment]
FWIW, we still see these occasionally (or 503s) but we're going to work around it at a higher level (basically our plan is to treat pub and pub's network dependencies as unreliable and retry a few times on the client in case of error).

**Comment by Hixie** [comment]
FWIW, AppVeyor has been seeing this all day. You can see many of our commits are red because of it:
https://github.com/flutter/flutter/commits/master

**Comment by cbracken** [comment]
Getting a bunch of 503 errors this morning from pub.dartlang.org.

**Comment by mkustermann** [comment]
This is a different issue than the one which has been fixed.

The sporadic 500s today started due to the datastore service returning "internal errors". After a conversation with the oncall this is now tracked at b/62226141.

**Comment by cbracken** [comment]
sgtm -- thanks!

**Comment by mkustermann** [comment]
This specific 500 issue has been addressed by cloud infrastructure teams in **b/62226141** .
